# Generated by Django 3.2.5 on 2021-07-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarRentApp.carengine'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarRentApp.steeringwheel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarRentApp.transmissiontype'),
        ),
    ]
