# Generated by Django 3.2.5 on 2021-07-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
