# Generated by Django 3.2.5 on 2021-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0002_auto_20210705_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='car_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(),
        ),
    ]
