# Generated by Django 3.2.5 on 2021-07-15 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0002_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message=['Մուտքագրեք իրական թվական բռատ'], regex='\\s+(?:19\\d{2}|20[01][0-9]|2020)')]),
        ),
    ]
