# Generated by Django 3.2.5 on 2021-07-05 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarRentApp', '0003_auto_20210705_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpost',
            name='user',
        ),
        migrations.AddField(
            model_name='carpost',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
