# Generated by Django 3.2.5 on 2021-07-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0008_car_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='added',
            new_name='added_by',
        ),
    ]
