# Generated by Django 3.2.5 on 2021-07-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0009_rename_added_car_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='added_by',
            new_name='creator',
        ),
    ]
