# Generated by Django 3.2.5 on 2021-07-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0013_carpost_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpost',
            old_name='added_by',
            new_name='added',
        ),
    ]
