# Generated by Django 3.2.5 on 2021-07-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApp', '0014_rename_added_by_carpost_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpost',
            name='added',
        ),
    ]
